package com.tqretail.pruebaclientevf;

/**
 * Please modify this class to meet your needs This class is not complete
 */
import https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.sistemafacturacion_wsdl.SfPortTypeVerifactu;
import https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.sistemafacturacion_wsdl.SfVerifactu;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.GeneralSecurityException;
import java.security.KeyStore;
import java.util.logging.Level;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.TrustManagerFactory;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 3.5.11 2025-03-27T18:24:29.702+01:00
 * Generated source version: 3.5.11
 *
 */
public final class SfPortTypeVerifactu_SistemaVerifactuPruebas_Client {

    private static final Logger log = LoggerFactory.getLogger(SfPortTypeVerifactu_SistemaVerifactuPruebas_Client.class);
    private static final QName SERVICE_NAME = new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SistemaFacturacion.wsdl", "sfVerifactu");

    private SfPortTypeVerifactu_SistemaVerifactuPruebas_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        String certificado = "CERTFF_2019.P12";         // FirstFruit

        File fCert = new File("./conf/" + certificado);
        if (!fCert.exists()) {
            String msg = "No encontrado certificado digital indicado:" + fCert.getAbsolutePath();
            System.out.println(msg);
        }
        log.error("hola");
        System.setProperty("javax.net.ssl.keyStore", "./conf/" + certificado);
        System.setProperty("javax.net.ssl.keyStoreType", "PKCS12");
        System.setProperty("javax.net.ssl.keyStorePassword", "270983"); // FirstFruit

        URL wsdlURL = SfVerifactu.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SfVerifactu ss = new SfVerifactu(wsdlURL, SERVICE_NAME);
        SfPortTypeVerifactu port = ss.getSistemaVerifactuPruebas();
   try {
            setupTLS(port);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(PruebaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (GeneralSecurityException ex) {
            java.util.logging.Logger.getLogger(PruebaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        {
            System.out.println("Invoking regFactuSistemaFacturacion...");
            https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.CabeceraType _regFactuSistemaFacturacion_cabeceraVal = null;
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.CabeceraType> _regFactuSistemaFacturacion_cabecera = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.CabeceraType>(_regFactuSistemaFacturacion_cabeceraVal);
            java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministrolr.RegistroFacturaType> _regFactuSistemaFacturacion_registroFactura = null;
            javax.xml.ws.Holder<java.lang.String> _regFactuSistemaFacturacion_csv = new javax.xml.ws.Holder<java.lang.String>();
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.DatosPresentacionType> _regFactuSistemaFacturacion_datosPresentacion = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.DatosPresentacionType>();
            javax.xml.ws.Holder<java.lang.String> _regFactuSistemaFacturacion_tiempoEsperaEnvio = new javax.xml.ws.Holder<java.lang.String>();
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestasuministro.EstadoEnvioType> _regFactuSistemaFacturacion_estadoEnvio = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestasuministro.EstadoEnvioType>();
            javax.xml.ws.Holder<java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestasuministro.RespuestaExpedidaType>> _regFactuSistemaFacturacion_respuestaLinea = new javax.xml.ws.Holder<java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestasuministro.RespuestaExpedidaType>>();
            port.regFactuSistemaFacturacion(_regFactuSistemaFacturacion_cabecera, _regFactuSistemaFacturacion_registroFactura, _regFactuSistemaFacturacion_csv, _regFactuSistemaFacturacion_datosPresentacion, _regFactuSistemaFacturacion_tiempoEsperaEnvio, _regFactuSistemaFacturacion_estadoEnvio, _regFactuSistemaFacturacion_respuestaLinea);

            System.out.println("regFactuSistemaFacturacion._regFactuSistemaFacturacion_cabecera=" + _regFactuSistemaFacturacion_cabecera.value);
            System.out.println("regFactuSistemaFacturacion._regFactuSistemaFacturacion_csv=" + _regFactuSistemaFacturacion_csv.value);
            System.out.println("regFactuSistemaFacturacion._regFactuSistemaFacturacion_datosPresentacion=" + _regFactuSistemaFacturacion_datosPresentacion.value);
            System.out.println("regFactuSistemaFacturacion._regFactuSistemaFacturacion_tiempoEsperaEnvio=" + _regFactuSistemaFacturacion_tiempoEsperaEnvio.value);
            System.out.println("regFactuSistemaFacturacion._regFactuSistemaFacturacion_estadoEnvio=" + _regFactuSistemaFacturacion_estadoEnvio.value);
            System.out.println("regFactuSistemaFacturacion._regFactuSistemaFacturacion_respuestaLinea=" + _regFactuSistemaFacturacion_respuestaLinea.value);

        }
        {
            System.out.println("Invoking consultaFactuSistemaFacturacion...");
            https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.CabeceraConsultaSf _consultaFactuSistemaFacturacion_cabeceraVal = null;
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.CabeceraConsultaSf> _consultaFactuSistemaFacturacion_cabecera = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.CabeceraConsultaSf>(_consultaFactuSistemaFacturacion_cabeceraVal);
            https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.consultalr.LRFiltroRegFacturacionType _consultaFactuSistemaFacturacion_filtroConsulta = null;
            https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.consultalr.DatosAdicionalesRespuestaType _consultaFactuSistemaFacturacion_datosAdicionalesRespuesta = null;
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.RespuestaConsultaType.PeriodoImputacion> _consultaFactuSistemaFacturacion_periodoImputacion = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.RespuestaConsultaType.PeriodoImputacion>();
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.IndicadorPaginacionType> _consultaFactuSistemaFacturacion_indicadorPaginacion = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.IndicadorPaginacionType>();
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.ResultadoConsultaType> _consultaFactuSistemaFacturacion_resultadoConsulta = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.ResultadoConsultaType>();
            javax.xml.ws.Holder<java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.RegistroRespuestaConsultaRegFacturacionType>> _consultaFactuSistemaFacturacion_registroRespuestaConsultaFactuSistemaFacturacion = new javax.xml.ws.Holder<java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.respuestaconsultalr.RegistroRespuestaConsultaRegFacturacionType>>();
            javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.IDFacturaExpedidaBCType> _consultaFactuSistemaFacturacion_clavePaginacion = new javax.xml.ws.Holder<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.suministroinformacion.IDFacturaExpedidaBCType>();
            port.consultaFactuSistemaFacturacion(_consultaFactuSistemaFacturacion_cabecera, _consultaFactuSistemaFacturacion_filtroConsulta, _consultaFactuSistemaFacturacion_datosAdicionalesRespuesta, _consultaFactuSistemaFacturacion_periodoImputacion, _consultaFactuSistemaFacturacion_indicadorPaginacion, _consultaFactuSistemaFacturacion_resultadoConsulta, _consultaFactuSistemaFacturacion_registroRespuestaConsultaFactuSistemaFacturacion, _consultaFactuSistemaFacturacion_clavePaginacion);

            System.out.println("consultaFactuSistemaFacturacion._consultaFactuSistemaFacturacion_cabecera=" + _consultaFactuSistemaFacturacion_cabecera.value);
            System.out.println("consultaFactuSistemaFacturacion._consultaFactuSistemaFacturacion_periodoImputacion=" + _consultaFactuSistemaFacturacion_periodoImputacion.value);
            System.out.println("consultaFactuSistemaFacturacion._consultaFactuSistemaFacturacion_indicadorPaginacion=" + _consultaFactuSistemaFacturacion_indicadorPaginacion.value);
            System.out.println("consultaFactuSistemaFacturacion._consultaFactuSistemaFacturacion_resultadoConsulta=" + _consultaFactuSistemaFacturacion_resultadoConsulta.value);
            System.out.println("consultaFactuSistemaFacturacion._consultaFactuSistemaFacturacion_registroRespuestaConsultaFactuSistemaFacturacion=" + _consultaFactuSistemaFacturacion_registroRespuestaConsultaFactuSistemaFacturacion.value);
            System.out.println("consultaFactuSistemaFacturacion._consultaFactuSistemaFacturacion_clavePaginacion=" + _consultaFactuSistemaFacturacion_clavePaginacion.value);

        }

        System.exit(0);
    }
 private static void setupTLS(SfPortTypeVerifactu port)
        throws IOException, GeneralSecurityException {
        final TLSClientParameters tlsCP = new TLSClientParameters();
        tlsCP.setDisableCNCheck(true);

        final KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
//        try (InputStream is = new FileInputStream("src/main/config/clientKeystore.jks")) {
//            keyStore.load(is, "cspass".toCharArray());
//        }
        try (InputStream is = new FileInputStream("./conf/CERTFF_2019.P12")) {
            keyStore.load(is, "270983".toCharArray());
        }

        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(keyStore, "270983".toCharArray());
        tlsCP.setKeyManagers(kmf.getKeyManagers());

        TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        tmf.init(keyStore);
        tlsCP.setTrustManagers(tmf.getTrustManagers());

        ((HTTPConduit) ClientProxy.getClient(port).getConduit()).setTlsClientParameters(tlsCP);
    }

}
